global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # YouTube Comment Intelligence API
  - job_name: 'youtube-comment-intelligence-api'
    static_configs:
      - targets: ['api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # YouTube Comment Intelligence Web UI
  - job_name: 'youtube-comment-intelligence-web'
    static_configs:
      - targets: ['web:8501']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Celery Workers
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['celery-worker:5555']

  # Flower (Celery monitoring)
  - job_name: 'flower'
    static_configs:
      - targets: ['flower:5555']

  # Node Exporter (if running on host)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323'] 